config/routes.rb
require 'crono/web'
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'homes#index'

  mount AirAppV1API => '/api/v1'
  mount Crono::Web, at: '/job_web'
  mount Resque::Server, :at => "/resque"
  mount Sidekiq::Web => '/sidekiq_web'
  resources :s_area_logins
  resources :d_abnormal_data_yyyymms
  resources :s_role_msgs
  resources :log_queries, only:[:index,:show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "get_branchs", on: :collection        #获取所有的分公司
    get "get_region_codes", on: :collection   #获取分公司下的所有车间或部门
    post 'get_datas', on: :collection
  end
  resources :test_iframes
  resources :handle_station_regions
  resources :reset_pds

  
  resources :s_func_msgs
  resources :homes, only:[:index]
  resources :file_maintenances do
    post "edit_new", on: :collection
  end
  resources :file_categories

  resources :d_stations do
    get "all_stations", on: :collection
    get 'area_logins', on: :member
    post 'handle_station', on: :member 
    put 'update_station', on: :member
  end
  resources :exception_monitorings  do  #ycjk
    get "init", on: :collection
  end
  resources :exception_sets  #ycSL
  resources :factors  # yz
  resources :get_obj_types  #jkdx
  resources :consults  #ckz
  resources :s_administrative_areas #xzqy

  resources :alarm_sets #bjsz
  resources :alarm_monitorings do#bjjk
    get "init_index", on: :collection
  end
  resources :alarm_lists  #bjhz
  resources :alarm_maps do  #bjdt
    get "init_index", on: :collection
  end
  resources :s_alarm_types #bjfl
  resources :s_alarm_levels  #bjjb
  resources :d_alarms

  resources :alarm_notices  #bjtz
  resources :alarm_notice_sets  #bjtzsz

  resources :alarm_despatches do #报警任务g
    get "despatch_infos", on: :collection
  end
  resources :alarm_despatch_sets #报警任务设置
  resources :search_station_logins do #站点管理区域人员
    post "despatch_create", on: :collection
  end
  resources :s_slas #SLA设置

  resources :alarm_num_statistics do # 统计
    get "init_index", on: :collection
    get "export_file", on: :collection
  end
  resources :alarm_num_scales do # 占比
    get "export_file", on: :collection
  end

  resources :alarm_num_time_analyse do  #时段
    get "export_file", on: :collection
  end
  resources :alarm_num_handles do   # 处理
    get "export_file", on: :collection
  end
  resources :search_alarm_num_handles do  #反馈查询
    get "export_file", on: :collection
  end
  resources :station_data_off do  #  站点离线时长统计
    get "export_file", on: :collection
  end

  resources :station_validity_data  #  站点24小时有效数据

  resources :alarm_num_trend # 趋势  X
  resources :ops_day_reports   #运维日报  x
  resources :ops_week_reports  #运维周报  x
  resources :ops_month_reports  #运维月报  x
  resources :ops_polling_week_reports    #运维巡检周报  x
  resources :single_station_pollutants_analysis   #单站点多污染分析
  resources :more_station_pollutants_analysis   #多站点多污染分析
  resources :data_statistics do   #站点有效性统计
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :data_access_statistics do  #站点获取率统计
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :facility_fault_day_reports do #设备运行故障日报
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :superior_air_days do  #优良天数对比
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :contaminant_leves do   #污染天气级别分布
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :concentration_analysis do   #浓度值对比分析
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end

  resources :search_regin_codes
  resources :search_region_codes_all  #查询所有的车间、部门
  resources :search_region_codes_areas  #查询所有的车间、部门

  resources :search_regin_code_infos   #查询所有单位
  resources :search_region_codes       #根据分公司 查询车间  查询车间接口

  resources :daily_report do #日报表        车间生产上报
    get "report", on: :collection   #上报操作
  end

  resources :energy_report do       #能源上报      
    get "report", on: :collection   #上报操作
    get "water_report", on: :collection            #生物循环水报表  用电上报
    get "power_report", on: :collection            #用电上报
  end

  resources :steam_report do       #蒸汽上报      
    get "steam_report", on: :collection            
  end

  resources :quality_report do       #质量上报      
    get "quality_report", on: :collection            
  end

  resources :pollution_report do       #一次水排污统计上报      
    get "pollution_report", on: :collection          #排污上报    
    get "once_water_report", on: :collection          #一次水上报  
    get "report", on: :collection   #排污报表上报操作
  end

  resources :fermentation_plant_form do            #车间日报表
    get "plant_form_index", on: :collection        #首页

    get "fermentation_workshop", on: :collection   #发酵车间生产报表
    get "bake_shop", on: :collection               #烘包车间生产报表
    get "refining_workshop", on: :collection       #精制车间生产报表
    get "synthetic_workshop", on: :collection      #合成车间生产报表
  end

  resources :energy_daily_form do        #  能源日报表
    get "energy_index", on: :collection        #首页

    get "energy_form_power", on: :collection        #生物用电报表  
    get "energy_form_water", on: :collection        #生物用循环水报表
    get "energy_form_once_water", on: :collection   #一次水报表
    get "energy_form_pollution", on: :collection    #排污报表
    get "energy_form_steam", on: :collection        #蒸汽报表
  end

  resources :company_statement   do        
    get "index_table", on: :collection      #公司总报表
  end

  resources :company_month_statement   do        
    get "index_table", on: :collection      #公司月总报表
  end

  resources :developing    #临时首页  开发中提示

  resources :s_equips do
    get 'get_equips',on: :collection #根据车间获取到设备
    get 'set_status',on: :collection #禁用启用
    post 'create_spare', on: :collection #创建跟设备相关的备件信息
    get 'edit_spare',on: :collection
    post 'update_spare',on: :collection #修改跟设备相关的备件信息
    delete 'delete_spare',on: :collection #删除跟设备相关的备件信息
    get 'get_handle_equip',on: :collection #获取到设备维修记录

    post 'excel_import',on: :collection #从excel导入台账信息
  end

  resources :handle_equips do
    get 'get_equips',on: :collection #获取到登录人所属车间设备
    get 'get_spare',on: :collection #获取设备所属备件
    get 'get_boots', on: :collection #获取检查项
    get 'get_login', on: :collection #获取人员
    post 'issued',on: :collection #下发
    post 'carried_out',on: :collection #执行
  end

  resources :review_equips

  resources :d_equip_works do
    get 'get_boots',on: :collection #获取检查项
    post 'issued',on: :collection #下发
    post 'carried_out',on: :collection #执行
    get 'get_login', on: :collection #获取人员
    get 'get_equip_regions', on: :collection #新增页面，车间部门 数据
    post 'batch_create',on: :collection #批量新增点检
  end

  resources :d_equip_work_rules do
    get 'get_boots',on: :collection #获取检查项
    post 'issued',on: :collection #下发
    get 'get_login', on: :collection #获取人员
    get 'get_equip_regions', on: :collection #新增页面，车间部门 数据
  end

  resources :equips_area_manage do 
    get 'get_areas',on: :collection     #根据车间获取到车间下的区域
    get 'area_edit',on: :collection     #修改
  end
  resources :post_reports do  #车间岗位盘点报表
    get 'get_product',on: :collection     #发酵、酸化 交料产量详细
    get 'period_inventory',on: :collection     #期盘点 接口
  end
  resources :publics do
    get 'status', on: :collection
  end

  resources :search_regin_logins  # area logions
  resources :search_login_regins  #login area  ghglqy
  resources :search_station_bindings  #bdyz
  resources :search_abnormal_rules   #ycmb  infos
  resources :search_abnormarl_instances  #ycgzsl
  resources :search_region_levels #gsjb
  resources :search_map_provinces #province  省
  resources :search_map_cities #city  城市
  resources :search_map_city
  resources :search_by_status
  resources :search_by_province_alarm #bjsf city infos  城市预警
  resources :search_five_datas do #5.minutes data infos
    get "export_file", on: :collection
  end
  resources :search_stations # all stations
  resources :search_notice_templates

  resources :handle_station_bindings  #bdyz handle
  resources :handle_alarm_rules #bjtzgz

  resources :tests
  resources :func_models do #means
    get "modal_form", on: :member
    get "table_infos", on: :collection
  end

  resources :assist do
    get "download_explorer" , on: :collection
  end
  
  resources :work_pros
  resources :power_cut_records do
    get "power_audit", on: :member  #审核
    get "report", on: :member  #上报，完成
    get "get_all_msgs", on: :collection  #根据运维单位获取所有的运维人员
  end

  resources :s_region_code
  resources :fault_jobs do
    member do 
      post "audit"    #审核
      get "forword"   #转发
    end
  end

  resources :supplies
  resources :accs

  resources :equipment_infos

  resources :ops_audit do
    get "batch_audit", on: :collection  #批量审核的路由
    get "review", on: :member       #复核
  end
  resources :d_task_forms do
    get "get_form_module", on: :member       #根据工作项id获取表格模板信息
    get "save_form_module", on: :collection  #保存表格中的数据
    get "sign_in", on: :collection           #运维成员签到
  end

  resources :next_plan_manages do
    get "report", on: :collection   #上报操作
  end

  resources :create_station_plan do
    get "create_plan", on: :collection   #上报操作
  end

  resources :ops_week_plan_manages
  resources :ops_audit_manages do
    get "plan_audit", on: :collection  #单个审核的路由
    get "search_ops", on: :collection  #根据week_time查询
  end

  resources :search_region_codes #获取所属区域（单位）
  
  resources :s_item_job # 因子设备job
  resources :search_units # 根据站点获取单位
  resources :search_unit_pers #根据单位id获取人
  resources :search_unit_manys #获取全部单位及所属人员   派遣操作

  resources :all_stations_area #按区域显示站点信息（商丘客户需要）

  resources :pending_works
  resources :equip_mains
  resources :equip_calibration
  resources :next_mmm_work_jobs

  resources :statistic_place
  resources :plan_analysis do
    get "search_ops", on: :collection  #根据week_time查询
  end
  resources :order_completion do

app/models/test_iframe.rb
class TestIframe < ActiveRecord::Base

  def self.login_num

  end

  def self.sidekiq_create
    now_time = Time.now
    SidekiqMinuteWorker.perform_in(now_time)
    SidekiqHourWorker.perform_in( now_time.beginning_of_hour + 40.minutes)
    SidekiqAlarmRuleWorker.perform_in(now_time)
    SidekiqStationLostWorker.perform_in(now_time)
    SidekiqStationLengthWorker.perform_in( now_time.beginning_of_day + 1.hours)
    SidekiqStationItemavgWorker.perform_in(now_time.beginning_of_day + 1.hours + 45.minutes )
    SidekiqStationDayFlagWorker.perform_in(now_time.beginning_of_day + 1.hours + 18.minutes )
    SidekiqAqiHourWorker.perform_in(now_time.beginning_of_hour + 21.minutes )
    SidekiqAqiDayWorker.perform_in( now_time.beginning_of_day + 2.hours + 13.minutes)
  end

  def self.test
    # "黑龙江管理处	运维人员	黑龙江省	大庆市	大同区 拜梦亚	17603850532",
    [
    # "河南管理处 运维人员 河南 平顶山市	高压开关厂 李振 17603851019",
    # "河南管理处 运维人员 河南 平顶山市	规划设计院  李振 17603851019",
    # "河南管理处 运维人员 河南 平顶山市	新华旅馆 董志文 17839213109",
    # "河南管理处 运维人员 河南 平顶山市	工学院 董志文 17839213109",
    # "河南管理处 运维人员 河南 平顶山市	高新区 李振 17603851019",
    # "河南管理处 运维人员 河南 许昌市	开发区 孙万华 15537852171",
    # "河南管理处 运维人员 河南 许昌市	监测站 孙万华 15537852171",
    # "河南管理处 运维人员 河南 漯河市	三五一五 麻建勋 176003853357",
    # "河南管理处 运维人员 河南 漯河市	广电局 麻建勋 176003853357",
    # "河南管理处 运维人员 河南 漯河市	漯河大学 严田田 176003852885",
    # "河南管理处 运维人员 河南 漯河市	水利局 严田田 176003852885",
    # "河南管理处 运维人员 河南 南阳市	环保局 李赛迪 15137517015",
    # "河南管理处 运维人员 河南 南阳市	瓦房庄 李赛迪 15137517015",
    # "河南管理处 运维人员 河南 南阳市	汉画馆 李赛迪 15137517015",
    # "河南管理处 运维人员 河南 南阳市	气象站 李赛迪 15137517015",
    # "河南管理处 运维人员 河南 南阳市	理工学院 李赛迪 15137517015",
    # "河南管理处 运维人员 河南 商丘市	环境监测站 孙久恒 17603853257",
    # "河南管理处 运维人员 河南 商丘市	粮食局 孙久恒 17603853257",
    # "河南管理处 运维人员 河南 商丘市	睢阳区环保局 孙久恒 17603853257",
    # "河南管理处 运维人员 河南 信阳市	南湾水厂 黄源 17603850332",
    # "河南管理处 运维人员 河南 信阳市	平桥分局 黄源 17603850332",
    # "河南管理处 运维人员 河南 信阳市	市酿酒公司 黄源 17603850332",
    # "河南管理处 运维人员 河南 信阳市	职业技术学院/市政府 黄源 17603850332",
    # "河南管理处 运维人员 河南 周口市	市环境监测站 齐康 17603852836",
    # "河南管理处 运维人员 河南 周口市	周口师范 齐康 17603852836",
    # "河南管理处 运维人员 河南 周口市	市运管处 齐康 17603852836",
    # "河南管理处 运维人员 河南 周口市	川汇区环保局 齐康 17603852836",
    # "河南管理处 运维人员 河南 周口市	文昌生态园/港区 齐康 17603852836",
    # "河南管理处 运维人员 河南 驻马店市	市一纸厂 王家庆 17603850519",
    # "河南管理处 运维人员 河南 驻马店市	市彩印厂 王家庆 17603850519",
    # "河南管理处 运维人员 河南 驻马店市	天方二分厂 许赛男 17603851851",
    ].each do | indo|
        arr = indo.split(" ")
        grop_id = SRegionCode.find_by(:region_name => "河南管理处")
        role = SRoleMsg.find_by(:role_name => "运维人员")
        puts "////#{arr[3] + "-" + arr[4][0,2]}"
        name = arr[3] + "-" + arr[4][0,2]
        station = DStation.where("station_name like ?" , "%#{name}%").first
        next if station.blank?
        begin
          login = DLoginMsg.create( login_no: Pinyin.t(arr[5], splitter: ''),
                                    login_name: arr[5],
                                    password: "111111",
                                    password_confirmation: "111111",
                                    group_id: grop_id.id,
                                    s_role_msg_id: role.id,
                                    valid_flag: 1,
                                    telphone: arr[6].present? ? arr[6][0,11] : "")
        rescue Exception => e

          login =  DLoginMsg.find_by(:login_name => arr[5])
        end
        next if login.blank?
        next if station.d_login_msgs.present?
        station.s_area_logins.create(:d_login_msg_id => login.id)
    end
  end

end

app/controllers/test_iframes_controller.rb
class TestIframesController < ApplicationController
  before_action :set_test_iframe, only: [:show, :edit, :update, :destroy]

  # GET /test_iframes
  # GET /test_iframes.json
  def index

    @test_iframes = TestIframe.all

    # @stations = DStation.all
    # @info = []
    # @stations.each do |station|
    #   logins = station.d_login_msgs
    #
    #   if logins.blank?
    #     @info << {id: station.id, station_name: station.station_name, login_name: "", telphone: ''}
    #   else
    #     logins.map {|x|  @info << {id: station.id, station_name: station.station_name, login_name: x.login_name, telphone: ""}  if x.telphone.blank? }
    #   end
    # end
    # @scv = CSV.generate(encoding: "GB18030") do |csv|
    #   csv << ["站点ID", "站点名称", "人员姓名", "电话"]
    #   @info.each do |info|
    #     csv << [info[:id], info[:station_name], info[:login_name],info[:telphone]]
    #   end
    # end
    #
    # @name = Time.now.strftime("%Y-%m-%d-") + "站点人员补漏"
    # respond_to do |format|
    #   format.html{}
    #   format.csv {
    #     send_data @scv,
    #               :type => 'text/csv; charset=GB18030; header=present',
    #               :disposition => "attachment; filename=#{@name}.csv"
    #   }
    # end

    # #render layout: false
    # respond_to do |format|
    #   format.html { render :index, status: :ok }
    #   format.json { render :index, status: :ok }
    # end
  end

  def download_explorer
    file_apth = "#{Rails.root}/public/app/android-app.apk"
    send_file(file_apth)
  end

  # GET /test_iframes/1
  # GET /test_iframes/1.json
  def show
  end

  # GET /test_iframes/new
  def new
    @test_iframe = TestIframe.new
  end

  # GET /test_iframes/1/edit
  def edit
  end

  # POST /test_iframes
  # POST /test_iframes.json
  def create
    @test_iframe = TestIframe.new(test_iframe_params)

    respond_to do |format|
      if @test_iframe.save
        format.html {redirect_to @test_iframe, notice: 'Test iframe was successfully created.'}
        format.json {render :show, status: :created, location: @test_iframe}
      else
        format.html {render :new}
        format.json {render json: @test_iframe.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /test_iframes/1
  # PATCH/PUT /test_iframes/1.json
  def update
    respond_to do |format|
      if @test_iframe.update(test_iframe_params)
        format.html {redirect_to @test_iframe, notice: 'Test iframe was successfully updated.'}
        format.json {render :show, status: :ok, location: @test_iframe}
      else
        format.html {render :edit}
        format.json {render json: @test_iframe.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /test_iframes/1
  # DELETE /test_iframes/1.json
  def destroy
    @test_iframe.destroy
    respond_to do |format|
      format.html {redirect_to test_iframes_url, notice: 'Test iframe was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_test_iframe
    @test_iframe = TestIframe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def test_iframe_params
    params.require(:test_iframe).permit(:mark, :yangna)
  end
end

app/helpers/test_iframes_helper.rb
module TestIframesHelper
end

app/views/test_iframes/_form.html.erb
<%= form_for(@test_iframe) do |f| %>
  <% if @test_iframe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_iframe.errors.count, "error") %> prohibited this test_iframe from being saved:</h2>

      <ul>
      <% @test_iframe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mark %><br>
    <%= f.text_field :mark %>
  </div>
  <div class="field">
    <%= f.label :yangna %><br>
    <%= f.text_field :yangna %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_iframes/_password.html.erb
<script id="resetPwd" type="text/html">
	<div class="reset_password">
		<h4>修改密码 <span class="pull-right" >X</span></h4>
		<form>
	    <div class="form-group">
	       <label class="col-xs-2 control-label passFontSize" for="passwd">新密码：</label>
	        <div class="col-xs-5">
	        	<input type="password"  required="required" pattern="^[a-zA-Z0-9]{2,16}$" class="form-control dateTimepicker" name="passwd" id="passwd"  value="" placeholder="请输入新密码"/>
	        </div>
	        <label id="passwdTip" class="col-xs-3 control-label colreset">请输入2-16位的数字</label>
	    </div>
	    <div class="clear">	    	</div>
	    <div class="form-group">
	       <label class="col-xs-2 control-label passFontSizes" for="passwd_ag">确认密码：</label>
	        <div class="col-xs-5">
	        	<input type="password"  required="required" pattern="^[a-zA-Z0-9]{2,16}$" class="form-control dateTimepicker" name="passwd_ag" id="passwd_ag"  value="" placeholder="请再次输入新密码"/>
	        </div>
	        <label id="passwd_confirmationTip" class="col-xs-3 control-label colreset">请输入2-16位的数字</label>
	    </div>
	    <div class="clear">	    	</div>
	    <div class="form-group">
	    	<div style="text-align: right; margin-top: 30px; margin-right: 20px;">
	    		<button type="button" class="btn btn-success " id="fix_pd">确认</button>
	            <button type="button" class="btn btn-default " id="fix_qx">取消</button>
	    	</div>
	    </div>
       </form>
    </div>
</script>  

app/views/test_iframes/_public_station.html.erb
<!--站点-->
	<div id="search-station">
		<div class="choose-site">
			
		</div>
	</div>
	<script id="editStations" type="text/html">
		
		<div class="tab-top">
			<span class="station-all">
				<input type="checkbox" />
				全部
			</span>
			{{each area_stations as Station index }}
				{{each Station.chil as station index }}
					<small>{{station.region_chil.id}}</small>
					<span class="top_region">{{station.region_chil.region_name}}</span>
				{{/each}}
			{{/each}}
		</div>
		<div class="station_content">
			{{each area_stations as Station index }}
				{{each Station.chil as station index }}
				<div class="list-station">
					<div class="tab-station">
						<p class="list-city">
							<span>
								<input type="checkbox" value="{{station.region_chil.id}}"/>
								<small>{{station.region_chil.id}}</small>
								<a>{{station.region_chil.region_name}}</a>
							</span>
						</p>
						<i class="search-line"></i>
						<br />
						{{each station.d_stations as dStations index}}
							<p class="list-city-station">
								<span>
									<input type="checkbox" value="{{dStations.id}}"/>
									<small>{{dStations.id}}</small>
									<a>{{dStations.station_name}}</a>
								</span>
							</p>
							<i class="search-line"></i>
						{{/each}}
					</div>
				</div>
				{{/each}}
			{{/each}}
		</div>
		<div class="station-btn">
			<span class="btn-sure">确定</span>
			<span class="btn-cancel">取消</span>
		</div>
	</script>

app/views/test_iframes/_sq_publicStation.html.erb
<div class="modal fade sq_station" id="sq_station" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">选择站点</h4>
      </div>
      <div class="modal-body station_contents">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default " data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-primary btn-sure">保存</button>
      </div>
    </div>
  </div>
</div>
<script type="text/html" id="stations">
	<div class="tab-top">
		<span class="station-all">
			<input type="checkbox" />
			全部
		</span>
		{{each stations as Station index }}
			<span class="top_region">{{Station.name}}</span>
		{{/each}}
	</div>
	<div class="station_content">
		{{each stations as Station index }}
			
			<div class="list-station">
				<div class="tab-station">
					<p class="list-city">
						<label>
							<span>
								<input type="checkbox" value=""/>
								
								<a>{{Station.name}}</a>
							</span>
						</label>
					</p>
					<i class="search-line"></i>
					<br />
					{{each Station.station as dStations index}}
						<p class="list-city-station">
							<label>
								<span>
									<input type="checkbox" value="{{dStations.id}}"/>
									<small class="hide">{{dStations.id}}</small>
									<a>{{dStations.station_name}}</a>
								</span>
							</label>
						</p>
						<i class="search-line"></i>
					{{/each}}
				</div>
			</div>
		
		{{/each}}
	</div>
</script>

app/views/test_iframes/_sq_radioStation.html.erb
<div class="modal fade sq_station" id="sq_radioStation" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">选择站点</h4>
      </div>
      <div class="modal-body station_contents">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default " data-dismiss="modal">取消</button>
        <button type="button" class="btn btn-primary btn-sure">保存</button>
      </div>
    </div>
  </div>
</div>
<script type="text/html" id="Addstations">
	<div class="tab-top">
		<span class="station-all">
			
			全部
		</span>
		{{each stations as Station index }}
			<span class="top_region">{{Station.name}}</span>
		{{/each}}
	</div>
	<div class="station_content">
		{{each stations as Station index }}
			
			<div class="list-station">
				<div class="tab-station">
					<p class="list-city">
						<span>
							
							<a>{{Station.name}}</a>
						</span>
					</p>
					<i class="search-line"></i>
					<br />
					{{each Station.station as dStations index}}
						<p class="list-city-station">
							<label>
								<span>
									<input type="radio" value="{{dStations.id}}" name="station"/>
									<small class="hide">{{dStations.id}}</small>
									<a>{{dStations.station_name}}</a>
								</span>
							</label>
						</p>
						<i class="search-line"></i>
					{{/each}}
				</div>
			</div>
		
		{{/each}}
	</div>
</script>

app/views/test_iframes/_station_radio.html.erb
<!--站点-->
	<div id="search-station2">
		<div class="choose-site">
			
		</div>
	</div>
	<script id="add_editStations" type="text/html">
		
		<div class="tab-top">
			<span class="station-all">
				
				全部
			</span>
			{{each area_stations as Station index }}
				{{each Station.chil as station index }}
					<small>{{station.region_chil.id}}</small>
					<span class="top_region">{{station.region_chil.region_name}}</span>
				{{/each}}
			{{/each}}
		</div>
		<div class="station_content">
			{{each area_stations as Station index }}
				{{each Station.chil as station index }}
				<div class="list-station">
					<div class="tab-station">
						<p class="list-city">
							<span>
								<small>{{station.region_chil.id}}</small>
								<a>{{station.region_chil.region_name}}</a>
							</span>
						</p>
						<i class="search-line"></i>
						<br />
						{{each station.d_stations as dStations index}}
							<p class="list-city-station">
								<span>
									<input type="radio" value="{{dStations.id}}" name="ss"/>
									<small>{{dStations.id}}</small>
									<a>{{dStations.station_name}}</a>
								</span>
							</p>
							<i class="search-line"></i>
						{{/each}}
					</div>
				</div>
				{{/each}}
			{{/each}}
		</div>
		<div class="station-btn">
			<span class="btn-sure">确定</span>
			<span class="btn-cancel">取消</span>
		</div>
	</script>

app/views/test_iframes/edit.html.erb
<h1>Editing Test Iframe</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_iframe %> |
<%= link_to 'Back', test_iframes_path %>

app/views/test_iframes/new.html.erb
<h1>New Test Iframe</h1>

<%= render 'form' %>

<%= link_to 'Back', test_iframes_path %>

app/views/test_iframes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mark:</strong>
  <%= @test_iframe.mark %>
</p>

<p>
  <strong>Yangna:</strong>
  <%= @test_iframe.yangna %>
</p>

<%= link_to 'Edit', edit_test_iframe_path(@test_iframe) %> |
<%= link_to 'Back', test_iframes_path %>