config/routes.rb
require 'crono/web'
require 'sidekiq/web'
Rails.application.routes.draw do

  root 'homes#index'

  mount AirAppV1API => '/api/v1'
  mount Crono::Web, at: '/job_web'
  mount Resque::Server, :at => "/resque"
  mount Sidekiq::Web => '/sidekiq_web'
  resources :s_area_logins
  resources :d_abnormal_data_yyyymms
  resources :s_role_msgs
  resources :log_queries, only:[:index,:show]
  resources :sessions, only:[:new, :create, :destroy]
  resources :d_login_msgs do
    get "get_branchs", on: :collection        #获取所有的分公司
    get "get_region_codes", on: :collection   #获取分公司下的所有车间或部门
    post 'get_datas', on: :collection
  end
  resources :test_iframes
  resources :handle_station_regions
  resources :reset_pds

  
  resources :s_func_msgs
  resources :homes, only:[:index]
  resources :file_maintenances do
    post "edit_new", on: :collection
  end
  resources :file_categories

  resources :d_stations do
    get "all_stations", on: :collection
    get 'area_logins', on: :member
    post 'handle_station', on: :member 
    put 'update_station', on: :member
  end
  resources :exception_monitorings  do  #ycjk
    get "init", on: :collection
  end
  resources :exception_sets  #ycSL
  resources :factors  # yz
  resources :get_obj_types  #jkdx
  resources :consults  #ckz
  resources :s_administrative_areas #xzqy

  resources :alarm_sets #bjsz
  resources :alarm_monitorings do#bjjk
    get "init_index", on: :collection
  end
  resources :alarm_lists  #bjhz
  resources :alarm_maps do  #bjdt
    get "init_index", on: :collection
  end
  resources :s_alarm_types #bjfl
  resources :s_alarm_levels  #bjjb
  resources :d_alarms

  resources :alarm_notices  #bjtz
  resources :alarm_notice_sets  #bjtzsz

  resources :alarm_despatches do #报警任务g
    get "despatch_infos", on: :collection
  end
  resources :alarm_despatch_sets #报警任务设置
  resources :search_station_logins do #站点管理区域人员
    post "despatch_create", on: :collection
  end
  resources :s_slas #SLA设置

  resources :alarm_num_statistics do # 统计
    get "init_index", on: :collection
    get "export_file", on: :collection
  end
  resources :alarm_num_scales do # 占比
    get "export_file", on: :collection
  end

  resources :alarm_num_time_analyse do  #时段
    get "export_file", on: :collection
  end
  resources :alarm_num_handles do   # 处理
    get "export_file", on: :collection
  end
  resources :search_alarm_num_handles do  #反馈查询
    get "export_file", on: :collection
  end
  resources :station_data_off do  #  站点离线时长统计
    get "export_file", on: :collection
  end

  resources :station_validity_data  #  站点24小时有效数据

  resources :alarm_num_trend # 趋势  X
  resources :ops_day_reports   #运维日报  x
  resources :ops_week_reports  #运维周报  x
  resources :ops_month_reports  #运维月报  x
  resources :ops_polling_week_reports    #运维巡检周报  x
  resources :single_station_pollutants_analysis   #单站点多污染分析
  resources :more_station_pollutants_analysis   #多站点多污染分析
  resources :data_statistics do   #站点有效性统计
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :data_access_statistics do  #站点获取率统计
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :facility_fault_day_reports do #设备运行故障日报
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :superior_air_days do  #优良天数对比
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :contaminant_leves do   #污染天气级别分布
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end
  resources :concentration_analysis do   #浓度值对比分析
    get 'init_index', on: :collection
    get "export_file", on: :collection
  end

  resources :search_regin_codes
  resources :search_region_codes_all  #查询所有的车间、部门
  resources :search_region_codes_areas  #查询所有的车间、部门

  resources :search_regin_code_infos   #查询所有单位
  resources :search_region_codes       #根据分公司 查询车间  查询车间接口

  resources :daily_report do #日报表        车间生产上报
    get "report", on: :collection   #上报操作
  end

  resources :energy_report do       #能源上报      
    get "report", on: :collection   #上报操作
    get "water_report", on: :collection            #生物循环水报表  用电上报
    get "power_report", on: :collection            #用电上报
  end

  resources :steam_report do       #蒸汽上报      
    get "steam_report", on: :collection            
  end

  resources :quality_report do       #质量上报      
    get "quality_report", on: :collection            
  end

  resources :pollution_report do       #一次水排污统计上报      
    get "pollution_report", on: :collection          #排污上报    
    get "once_water_report", on: :collection          #一次水上报  
    get "report", on: :collection   #排污报表上报操作
  end

  resources :fermentation_plant_form do            #车间日报表
    get "plant_form_index", on: :collection        #首页

    get "fermentation_workshop", on: :collection   #发酵车间生产报表
    get "bake_shop", on: :collection               #烘包车间生产报表
    get "refining_workshop", on: :collection       #精制车间生产报表
    get "synthetic_workshop", on: :collection      #合成车间生产报表
  end

  resources :energy_daily_form do        #  能源日报表
    get "energy_index", on: :collection        #首页

    get "energy_form_power", on: :collection        #生物用电报表  
    get "energy_form_water", on: :collection        #生物用循环水报表
    get "energy_form_once_water", on: :collection   #一次水报表
    get "energy_form_pollution", on: :collection    #排污报表
    get "energy_form_steam", on: :collection        #蒸汽报表
  end

  resources :company_statement   do        
    get "index_table", on: :collection      #公司总报表
  end

  resources :company_month_statement   do        
    get "index_table", on: :collection      #公司月总报表
  end

  resources :developing    #临时首页  开发中提示

  resources :s_equips do
    get 'get_equips',on: :collection #根据车间获取到设备
    get 'set_status',on: :collection #禁用启用
    post 'create_spare', on: :collection #创建跟设备相关的备件信息
    get 'edit_spare',on: :collection
    post 'update_spare',on: :collection #修改跟设备相关的备件信息
    delete 'delete_spare',on: :collection #删除跟设备相关的备件信息
    get 'get_handle_equip',on: :collection #获取到设备维修记录

    post 'excel_import',on: :collection #从excel导入台账信息
  end

  resources :handle_equips do
    get 'get_equips',on: :collection #获取到登录人所属车间设备
    get 'get_spare',on: :collection #获取设备所属备件
    get 'get_boots', on: :collection #获取检查项
    get 'get_login', on: :collection #获取人员
    post 'issued',on: :collection #下发
    post 'carried_out',on: :collection #执行
  end

  resources :review_equips

  resources :d_equip_works do
    get 'get_boots',on: :collection #获取检查项
    post 'issued',on: :collection #下发
    post 'carried_out',on: :collection #执行
    get 'get_login', on: :collection #获取人员
    get 'get_equip_regions', on: :collection #新增页面，车间部门 数据
    post 'batch_create',on: :collection #批量新增点检
  end

  resources :d_equip_work_rules do
    get 'get_boots',on: :collection #获取检查项
    post 'issued',on: :collection #下发
    get 'get_login', on: :collection #获取人员
    get 'get_equip_regions', on: :collection #新增页面，车间部门 数据
  end

  resources :equips_area_manage do 
    get 'get_areas',on: :collection     #根据车间获取到车间下的区域
    get 'area_edit',on: :collection     #修改
  end
  resources :post_reports do  #车间岗位盘点报表
    get 'get_product',on: :collection     #发酵、酸化 交料产量详细
    get 'period_inventory',on: :collection     #期盘点 接口
  end
  resources :publics do
    get 'status', on: :collection
  end

  resources :search_regin_logins  # area logions
  resources :search_login_regins  #login area  ghglqy
  resources :search_station_bindings  #bdyz
  resources :search_abnormal_rules   #ycmb  infos
  resources :search_abnormarl_instances  #ycgzsl
  resources :search_region_levels #gsjb
  resources :search_map_provinces #province  省
  resources :search_map_cities #city  城市
  resources :search_map_city
  resources :search_by_status
  resources :search_by_province_alarm #bjsf city infos  城市预警
  resources :search_five_datas do #5.minutes data infos
    get "export_file", on: :collection
  end
  resources :search_stations # all stations
  resources :search_notice_templates

  resources :handle_station_bindings  #bdyz handle
  resources :handle_alarm_rules #bjtzgz

  resources :tests
  resources :func_models do #means
    get "modal_form", on: :member
    get "table_infos", on: :collection
  end

  resources :assist do
    get "download_explorer" , on: :collection
  end
  
  resources :work_pros
  resources :power_cut_records do
    get "power_audit", on: :member  #审核
    get "report", on: :member  #上报，完成
    get "get_all_msgs", on: :collection  #根据运维单位获取所有的运维人员
  end

  resources :s_region_code
  resources :fault_jobs do
    member do 
      post "audit"    #审核
      get "forword"   #转发
    end
  end

  resources :supplies
  resources :accs

  resources :equipment_infos

  resources :ops_audit do
    get "batch_audit", on: :collection  #批量审核的路由
    get "review", on: :member       #复核
  end
  resources :d_task_forms do
    get "get_form_module", on: :member       #根据工作项id获取表格模板信息
    get "save_form_module", on: :collection  #保存表格中的数据
    get "sign_in", on: :collection           #运维成员签到
  end

  resources :next_plan_manages do
    get "report", on: :collection   #上报操作
  end

  resources :create_station_plan do
    get "create_plan", on: :collection   #上报操作
  end

  resources :ops_week_plan_manages
  resources :ops_audit_manages do
    get "plan_audit", on: :collection  #单个审核的路由
    get "search_ops", on: :collection  #根据week_time查询
  end

  resources :search_region_codes #获取所属区域（单位）
  
  resources :s_item_job # 因子设备job
  resources :search_units # 根据站点获取单位
  resources :search_unit_pers #根据单位id获取人
  resources :search_unit_manys #获取全部单位及所属人员   派遣操作

  resources :all_stations_area #按区域显示站点信息（商丘客户需要）

  resources :pending_works
  resources :equip_mains
  resources :equip_calibration
  resources :next_mmm_work_jobs

  resources :statistic_place
  resources :plan_analysis do
    get "search_ops", on: :collection  #根据week_time查询
  end
  resources :order_completion do

app/controllers/d_stations_controller.rb
class DStationsController < ApplicationController
  before_filter :authenticate_user
  before_action :set_d_station, only: [:show, :edit, :update, :destroy,:area_logins,:handle_station]
  before_action :current_user



  # GET /d_stations
  # GET /d_stations.json
  def index
    # code_arr = []
    code_hash = {}
    region_code = @current_user.s_region_code

    @s_station_code = @current_user.d_stations.page(params[:page]).per(params[:per])
    @regin_stations = @s_station_code.present? ? @s_station_code : []

    code_hash['chil'] = {region_chil: region_code ,d_stations: @s_station_code}
    @station_hash =[{region_chil: region_code ,d_stations: @s_station_code}]

    @station_id     = params[:station_id]
    @station_name   = params[:station_name]
    # @d_station_region_code = DStation.where( :region_code => @current_user.s_region_code.region_code ).page(params[:page]).per(params[:per])
    if @station_id.nil?
      @d_stations = @s_station_code
    # elsif @station_id.length == 0
    #   @d_stations = @d_station_region_code
    else
      @d_stations = @s_station_code.where( "id" => @station_id.split(",") )
    end
  end

  def all_stations
    if params[:station_ids].present?
      @d_stations = DStation.by_station_ids(params[:station_ids]).order(:created_at => :desc).page(params[:page]).per(10)
      return
    end

    @d_stations =  DStation.order(:created_at => :desc).page(params[:page]).per(params[:per])

  end
  # get /d_stations/:id/area_logins
  def area_logins
     arr = []
     # zone_ids = @d_station.s_area_logins.pluck
     area_code = @d_station.region_code
     # login_arr = @d_station.d_login_msgs.order(:id)

     @areas = SRegionCode.where(:region_code => area_code)
     @areas.each_with_index do |area,index|
       area_login_arr =  area.d_login_msgs.order(:id)
       # zone_login_arr <<  area_login_arr
       arr   <<  {area: area, logins: area_login_arr}
     end

       render json: {areas: arr}

  end

  # post /d_stations/:id/handle_station
  def handle_station
    flag = false
      if params[:login_arr].present?
        arr = params[:login_arr]
        arr.each do |login|
          if @d_station.s_area_logins.where(:d_login_msg_id => login).present?
            flag = true
             next
          else
            if @d_station.s_area_logins.where(:d_login_msg_id => login).present?
              @d_station.s_area_logins.where(:d_login_msg_id => login).first.delete
              flag = true
              next
            end

            if  @d_station.s_area_logins.create(:d_login_msg_id => login)
              flag = true
            else
              flag = false
            end
          end


        end
      end
      if flag
        render json: {location: "success", status: :ok}
      else
        render json: {location: "error",status: :unprocessable_entity}
      end
  end

  # put /d_stations/:id/update_station
  def update_station
    flag = false
    if params[:login_arr].present?
      arr = params[:login_arr]
      arr.each do |login|
        if  @d_station.s_area_logins.where(:d_login_msg_id => login).first.delete
          flag = true
        else
          flag = false
        end
      end
    end
    if flag
      render json: {location: "success", status: :ok}
    else
      render json: {location: "error",status: :unprocessable_entity}
    end
  end

  # GET /d_stations/1
  # GET /d_stations/1.json
  def show 
  end

  # GET /d_stations/new
  def new
    @d_station           = DStation.new
    @s_station_types     = SStationType.all
    @s_software_versions = SSoftwareVersion.all
    @s_region_codes      = SRegionCode.all
  end

  # GET /d_stations/1/edit
  def edit
    @s_station_types     = SStationType.all
    @s_software_versions = SSoftwareVersion.all
    @s_region_codes      = SRegionCode.all
  end

  # POST /d_stations
  # POST /d_stations.json
  def create
    retCode = true
    
    @d_station = DStation.new(d_station_params)
    # @area = SAdministrativeArea.find_by(:zone_rank =>@d_station.region_code)
    # @d_station.region_code = @area.zone_name
    # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code    = "d_stations|create"
    wLoginOpr.op_time    = Time.now.to_s
    wLoginOpr.login_no   = @current_user.login_no
    wLoginOpr.ip_addr    = @current_user.ip_address
    wLoginOpr.op_note    = "站点配置"
    wLoginOpr.op_describe = "新增站点配置信息"
    s_administrative_area = SAdministrativeArea.where(:zone_name => @d_station.region_code).first
    @d_station.region_code = s_administrative_area.zone_name if s_administrative_area.present?
    @d_station.s_administrative_area_id = s_administrative_area.id if s_administrative_area.present?
  
    #站点名
   @d_station.station_name = "#{@d_station.region_code}-#{@d_station.station_name}"
    
  retCode = wLoginOpr.save! if retCode
    respond_to do |format|
      if @d_station.save
        format.html { redirect_to  "/d_stations" }
        format.json { render json: {location: @d_station, status: :created  } }
      else
        format.html { render :new }
        format.json { render json: @d_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /d_stations/1 
  # PATCH/PUT /d_stations/1.json
  def update
    retCode   = true
    @onoff_flag     = params[:onoff_flag]
    ## 判断
    if @onoff_flag == "on"
      station_status = '1'
    else
      station_status = '0'    
    end
    if @onoff_flag
      retCode = @d_station.update( "station_status" => station_status )
    else
      s_administrative_area = SAdministrativeArea.where(:zone_name=> params[:d_station]["region_code"]).first
      params[:d_station]["region_code"] = s_administrative_area.zone_name  if s_administrative_area.present?
      params[:d_station]['s_administrative_area_id'] = s_administrative_area.id if s_administrative_area.present?
      retCode = @d_station.update( d_station_params )
    end
    respond_to do |format|
      if retCode
        format.html {  }
        format.json { render json:{ status: :ok, location: @d_station} }
      else
        format.html { render :edit }
        format.json { render json: @d_station.errors, status: :unprocessable_entity }
      end
    end
    
    
    # 写日志
    wLoginOpr = WLoginOpr.new
    wLoginOpr.op_code   = "d_stations|update"
    wLoginOpr.op_time   = Time.now.to_s
    wLoginOpr.login_no  = @current_user.login_no
    wLoginOpr.ip_addr   = @current_user.ip_address
    wLoginOpr.op_note   = "站点信息配置修改"
    wLoginOpr.op_describe = "站点信息配置修改"
    wLoginOpr.save
  end

  # DELETE /d_stations/1
  # DELETE /d_stations/1.json
  def destroy
    @d_station.destroy
    respond_to do |format|
      format.html { redirect_to d_stations_url, notice: 'D station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_d_station
      @d_station = DStation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def d_station_params
      params.require(:d_station).permit(:station_name, :region_code, :station_type,
                                        :wc_station_id, :object_id, :match_string, :station_location, :longitude,
                                        :latitude, :station_ip, :station_mac, :service_no, :setup_date,:created_at,
                                        :station_status, :is_online, :note, :soft_version_no,:s_administrative_area_id,
      :distance, :arrive_time )
    end
end

app/helpers/d_stations_helper.rb
module DStationsHelper

	def s_station_type
		@d_station.s_station_type
	end
	
end

app/views/d_stations/_form.html.erb
<div id="siteDeploy">
    <%= form_for(@d_station) do |f| %>
    <% if @d_station.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@d_station.errors.count, "error") %> prohibited this d_station from being saved:</h2>
        <ul>
            <% @d_station.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
	<%= @d_station.region_code %>
    <div class="field">
        <label>站点名称:</label>
        <%= f.text_field :station_name,required:"true",pattern:"^([\u4e00-\u9fa5]{2,16})$" %>
    </div>
    <div class="field">
        <label>区域归属:</label>
        <%= f.text_field :region_code,class:"chooseBox" %>
		<input class="choice" required="required" />
        <span class="btn btn-primary choose">选择</span>
    </div>
    <div class="field">
        <label>站点类型:</label>
        <%= select_tag "d_station[station_type]", options_from_collection_for_select(@s_station_types, "id", "type_name") %>
   </div>
    <div class="field">
        <label>地理位置:</label>
        <%= f.text_field :station_location,class:"location unable",required:"true" %>
        <span class="btn btn-primary mapView">地图选址</span>
    </div>
    <div class="field">
        <label>经度:</label>
        <%= f.text_field :longitude,class:"longLat unable",required:"true",pattern:"^[-+]?[0-9]*\.?[0-9]+$" %>
    </div>
    <div class="field">
        <label>纬度:</label>
        <%= f.text_field :latitude,class:"longGat unable",required:"true",pattern:"^[-+]?[0-9]*\.?[0-9]+$" %>
    </div>
    <div class="field">
        <label>服务号:</label>
        <%= f.text_field :service_no %>
    </div>
    <div class="field">
        <label>建站日期:</label>
        <%= f.text_field :setup_date,class:"some_class" %>
    </div>
    <div class="field">
        <label>版本号:</label>
		<%= select_tag "d_station[soft_version_no]", options_from_collection_for_select(@s_software_versions, "version_no", "version_no") %>
    </div>
    <div class="remark">
        <label>备注:</label>
        <%= f.text_area :note %>
    </div>
	<%= f.text_field :station_status,{value:'1',class:"hide"} %>
	<%= f.text_field :is_online,{value:'Y',class:"hide"} %>
    <div class="actions">
        <%= f.submit "确 认",class:"acknowledge btn btn-primary" %>
		<%= link_to '返回', d_stations_path,class:"btn btn-primary back"  %>
    </div>
    <% end %>
</div>
<!-- 地图容器 -->
<div id="allmap" style="display:none"></div>
<div class="close"><span class="glyphicon glyphicon-remove"></span></div>
<script type="text/javascript" src="http://api.map.baidu.com/api?key=&v=1.1&services=true"></script>
<script type="text/javascript">
   
// 百度地图API功能	
    $(function(){
        var map = new BMap.Map("allmap");
        map.centerAndZoom(new BMap.Point(113.630729, 34.73962), 11);
		 var point = new BMap.Point(113.630729,34.73962);
        map.centerAndZoom(point);
        var geoc = new BMap.Geocoder();
        map.enableScrollWheelZoom(true);
		map.enableContinuousZoom(); 
		map.onclick = function(e){
			var pt = e.point;
			geoc.getLocation(pt, function(rs){
                var addComp = rs.addressComponents;
				var place = addComp.province + ", " + addComp.city + ", " + addComp.district + ", " + addComp.street;
                if(confirm("当前选址："+place)){
					map.addEventListener("click");
					$('.location').val(place);
					 $(".longLat").val(e.point.lng);
					$(".longGat").val( e.point.lat);
					$("#allmap").css('display','none');
				}else{
					map.removeEventListener("click");
				};
			});
			console.log($("#newStation").height());
			//$("#aallmap #platform").css("over","auto");
			//$("#allmap #mask").css("height","100%");
		}
		
        /*单击事件*/
        $(".mapView").click(function(){
            $('#allmap').css('display','block');
			$('.close').css('display','block');
        });
		$('.close').click(function(){
			$("#allmap").css('display','none');
			$(this).css('display','none');
		})
		$(".choice").focus(function(){
		  this.blur();
		});
		$(".unable").focus(function(){
		  this.blur();
		});
		
		/*日期*/
		var time = new Date();
		var year = time.getFullYear();
		$('.some_class').datetimepicker({
			format:"Y-m-d",
			minDate:year+'-01-01',
			maxDate: year+'-12-31',
			todayButton:true,
			timepicker:false
		})
		var myMonth = time.getMonth()+1
		var myDate = time.getDate()-1
    });
</script>
<!-- 区域归属选择 -->
<div class="message">
    <div id="search" style="padding-left: 0;">
        <div id="search-station">
			<div class="choose-site">
				<div class="tab-top">
					<span class="station-all">
						<% if @current_user.s_region_code.is_leaf == "1" %>
							<%= @current_user.s_region_code.father_region.region_name %>
						<% else %>
							<%= @current_user.s_region_code.region_name %>
						<% end %>
					</span>
					
				</div>
				<div id="search-station">
					<div class="list-station">
						<% if @current_user.s_region_code.is_leaf == "1" %>
								<div class="tab-station">
									<span class="list-city">
										<span>
		
											<a href="#"><%= @current_user.s_region_code.region_name %></a>	
										</span>
									</span>
									<span class="search-line"></span>
								
									<% @current_user.s_region_code.d_stations.each do | dstation | %>
									<span class="list-city-station">
										<span>
											<input type="radio" class="radios" name="r" />
											<small style="display: none;"><%= dstation.region_code %></small>
											<a><%= dstation.station_name %></a>
										</span>
										<br />
									</span>
									<% end %>
								</div>
						<% else %>
						<% @current_user.s_region_code.son_region.each do | srgnc | %>
							<span class="tab-station " >
								<span class="list-city" >
									<span>
										<input type="radio" class="radios" name="r" />
										<small style="display: none;"><%= srgnc.region_code %></small>
										<a><%= srgnc.region_name %></a>
									</span>
								</span>
								<span class="search-line"></span>
							</span>
						<% end %>	
						<% end %>		
					</div>
					<div class="station-btn">
						<span class="btn-sure">确定</span>
						<span class="btn-cancel">取消</span>
					</div>
				</div>
			</div>
		</div>
    </div>
</div>
<script>
    $(function(){
//		站点
		$('.choose').click(function(){
			$('#search-station .choose-site').show()
		})
		$('#search-station .tab-top span').click(function(){
			var $index = $(this).index()
			$('#search-station .choose-site .tab-station').eq($index-1).show().siblings().hide()
			$(this).css('background','#fff').siblings().css('background','')
		})
		$('#search-station .tab-top span').eq(0).click(function(){
			$('#search-station .choose-site .tab-station').show()
		})
		
		$('#search-station .station-btn .btn-sure').click(function(){
			$('#search-station .choose-site').hide()
			if($('#search-station .choose-site  .radios:checked')){
				var text=[];
				var textid=[];
				$('#search-station  .radios:checked').siblings('small').each(function(){
					text.push(this.innerHTML)
				})
				$('#search-station  .radios:checked').siblings('a').each(function(){
					textid.push(this.innerHTML)
				})
				var allText = text.join(',')
				var textid=textid.join(',')
				$('.chooseBox').val(allText)
				$('.choice').val(textid)
			}else{
				$('#day-table .search-once .controll-station').val('')
				$('#day-table .search-once .selId').val('')
			}
		})
		$('#search-station .choose-site .tab-station').each(function(i){
			$(this).find('p span').click(function(){
				var check;
				$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').each(function(){
					if($(this).prop('checked')==false){
						check='false';
						return false
					}else{
						check='true'
					}
				})
				if(check=='true'){
					$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').prop('checked',true)
				}else{
					$('#search-station .choose-site .tab-station').eq(i).find('.list-city input').prop('checked',false)
				}
			})
		})	
		$('#search-station .station-btn .btn-cancel').click(function(){
			$('#search-station .choose-site').hide()
		})
	})	
</script>

app/views/d_stations/show.html.erb
<!--站点信息配置查询-->
<div class="deploy"><span class="glyphicon glyphicon-search"></span> 站点信息配置查询</div>
<div id="showStation">
	
	<div>
	  <strong>站点名称:</strong>
	  <span><%= @d_station.station_name %></span>
	</div>

	<div>
	  <strong>区域归属:</strong>
	  <span><%= @d_station.region_code %></span>
	</div>

	<div>
	  <strong>站点类型:</strong>
	  <span><%= @d_station.station_type %></span>
	</div>
	<div>
	  <strong>地理位置:</strong>
	  <span><%= @d_station.station_location %></span>
	</div>

	<div>
	  <strong>经度:</strong>
	  <span><%= @d_station.longitude %></span>
	</div>
	
	<div>
	  <strong>纬度:</strong>
	  <span><%= @d_station.latitude %></span>
	</div>
	<div>
	  <strong>站点IP:</strong>
	  <span><%= @d_station.station_ip %></span>
	</div>
	<div>
	  <strong>服务号:</strong>
	  <span><%= @d_station.service_no %></span>
	</div>
	<div>
	  <strong>建站日期:</strong>
	  <span><%= @d_station.setup_date.to_s[0..18]  %></span>
	</div>
	<div class="field">
		 <strong>版本号:</strong>
		 <span><%= @d_station.soft_version_no %></span>
	</div>
	<div class="remark">
		<strong>备注:</strong>
		<textarea><%= @d_station.note %></textarea>
	</div>

	<div class="showStationBtn">
		<%= link_to '编辑', edit_d_station_path(@d_station),class:"btn btn-success" %> 
		<%= link_to '返回', d_stations_path,class:"btn btn-success"  %>
	</div>
</div>